# This is a basic workflow to help you get started with Actions

name: Build Containers

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Separate builds for each container
  ubuntu_18-04:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
      - name: Build Ubuntu 18.04 Container
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.ubuntu18.04
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/performous-build:ubuntu18.04
          
  ubuntu_20-04:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Ubuntu 20.04 Container
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.ubuntu20.04
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/performous-build:ubuntu20.04

  fedora_32:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Fedora 32 Container
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.fedora32
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/performous-build:fedora32

  fedora_33:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Fedora 33 Container
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.fedora33
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/performous-build:fedora33

  fedora_34:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Fedora 34 Container
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.fedora34
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/performous-build:fedora34
